### ISSUE TITLE
XRay traces not connected to log entries in Cloudwatch

### ISSUE THREAD

**Issue by mpetrik-profinit** [aws-observability/aws-otel-java-instrumentation#205]
**Describe the bug**
We've migrated from Java X-Ray SDK to AWS OTEL. And the thing we are facing now is the absence of log records while analyzing traces. This worked with X-Ray SDK:
![image](https://user-images.githubusercontent.com/107056080/188083169-9fb5f1c9-d7b6-4435-a72c-cb5fd86cdfcf.png)

However, with OTEL, the logs are not mapped (we use Fluentbit). The only difference we've found in the metrics/traces messages (compared to XRay SDK) is the absence of the following key:
```
...
Segments: [
 {
  ...
  "document": {
   ....
   "aws": {
     ...
     "cloudwatch_logs": {
         "log_group": "our log group"
     ....
```

The aws.cloudwatch_logs.log_group is missing when using OTEL. The documentation says it translates from aws.log.group.names (https://aws-otel.github.io/docs/getting-started/x-ray#otel-span-cw-logs-metadata-translation).

**Steps to reproduce**
- Use EKS Cluster with OTEL collector (Sidecar: public.ecr.aws/aws-observability/aws-otel-collector:latest) and the following configuration:
```
    extensions:
      health_check:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      awsxray:
        endpoint: 0.0.0.0:2000
        transport: udp
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50
      batch/metrics:
        timeout: 60s
    exporters:
      awsxray:
        region: eu-west-1   
      awsemf:
        region: eu-west-1
    service:
      pipelines:
        traces:
          receivers: [otlp,awsxray]
          processors: [batch/traces]
          exporters: [awsxray]
        metrics:
          receivers: [otlp]
          processors: [batch/metrics]
          exporters: [awsemf]
      extensions: [health_check]
```
- Use Fluentbit to send logs to CloudWatch
- Use SpringBoot application v2.7.0 with OTEL agent (1.17.0-aws)

Call a REST Endpoint (the endpoint logs to console with Log4J2). The log is visible in Cloudwatch, the log entry contains AWS_XRAY_TRACE_ID.

**What did you expect to see?**
I see a log entry in the trace detail (as with the previous XRay SDK)

**What did you see instead?**
I see traces without log information, however, the log entries are visible in Log groups in Cloudwatch.

**Additional context**
We've tried configuration using environment properties (AWS_LOG_GROUP_NAMES/ARNS), in OTEL_RESOURCE_ATTRIBUTES, in span attributes, however, with no luck. Are we missing some kind of configuration (pod roles?) here?
